import Head from "next/head";
import { useRouter } from "next/router";

import classes from "../styles/Home.module.css";
import Translate from "../assets/Translate";
import en from "../assets/locales/en/translation";
import fr from "../assets/locales/fr/translation";

export default function Home() {
  const { locale } = useRouter();
  const lang = locale === "en" ? en : fr;

  return (
    <div className={classes.container}>
      <Head>
        <title>Olympiad | ClimateScience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>

      <main className={classes.main}>
        <form className={classes.card}>
          <Translate />

          <div className={classes.tab}>
            <h2 className={classes.ques}>{lang.question}</h2>
            <ul className={classes.options}>
              <li>
                <div className={classes.circle}>
                  <div className={classes.option__circle}></div>
                </div>
                <label className={classes.option}>{lang.option1}</label>
              </li>
              <li>
                <div className={classes.circle}>
                  <div className={classes.option__circle}></div>
                </div>
                <label className={classes.option}>{lang.option2}</label>
              </li>
              <li>
                <div className={classes.circle}>
                  <div className={classes.answer}></div>
                </div>
                <label className={classes.option}>{lang.option3}</label>
              </li>
            </ul>
          </div>
        </form>
      </main>
    </div>
  );
}
